name: fastapi-service
componentType: service
build:
  buildCommand: pip install -r requirements.txt
  runCommand: uvicorn apps.backend-fastapi.main:app --host=0.0.0.0 --port=8000
inbound:
  - name: http
    type: REST
    context: /
    port: 8000
