# This file is used to configure the component for the FastAPI service.
name: fastapi-service
componentType: service
spec:
  build:
    buildCommand: pip install -r requirements.txt
    runCommand: uvicorn main:app --host=0.0.0.0 --port=8000
  inbound:
    - name: http
      type: REST
      context: /
      port: 8000
